### PR TITLE
SQL and eslint

### PR DESCRIPTION
**Pull request by ryancwalsh**
2 commits (could be reviewed separately but are not very complicated):

- specifying fields in SQL instead of SELECT * (specificity will be especially [important](https://near-foundation.atlassian.net/browse/TTA-55?focusedCommentId=10905) for Databricks. We'll want to omit the fields that we don't care about.)
- eslint adjustments related to console logging

### CODE REVIEW

**Comment by PierreLeGuen** [comment]
Why is that important for DataBricks?

**Comment by ryancwalsh** [comment]
@PierreLeGuen My understanding is that Databricks stores data in massive files in GCP and that if we retrieve extra columns, the queries take longer. 

Also, even if we were pulling from normal tables, I've read that it's generally a good idea to specify which columns you want because it allows code to "fail fast and loud", which is better than if the schema changes and stuff breaks in a more subtle and confusing way.

**Review by PierreLeGuen — APPROVED** [review]
I saw that you disabled all console logs. Should we migrate to another logging lib? @ryancwalsh

**Comment by ryancwalsh** [comment]
@PierreLeGuen  This eslint rule could be good for preventing us from accidentally committing frontend `console.log` statements since our team seems to want to avoid those.

But it will also prevent backend `console.log` statements.

So I guess in a future PR someone could add support for Signale or WinstonJs: https://near-foundation.slack.com/archives/C03MASFG1GS/p1669994488912149?thread_ts=1669925161.667289&cid=C03MASFG1GS

**Comment by ryancwalsh** [comment]
I just looked at:

```
SELECT
    T.TRANSACTION_HASH,
    TA.ARGS,
    ARA.ARGS,
    ARA.RECEIPT_ID,
    ARA.ACTION_KIND
FROM
    TRANSACTIONS T
  LEFT JOIN RECEIPTS R ON (T.CONVERTED_INTO_RECEIPT_ID = R.RECEIPT_ID
            OR T.TRANSACTION_HASH = R.ORIGINATED_FROM_TRANSACTION_HASH)
    LEFT JOIN TRANSACTION_ACTIONS TA ON T.TRANSACTION_HASH = TA.TRANSACTION_HASH
    LEFT JOIN ACTION_RECEIPT_ACTIONS ARA ON ARA.RECEIPT_ID = R.RECEIPT_ID
where
  ARA.args != TA.args
limit 30;
```

which shows that the 2 `args` columns are not the same.

So I think our `SELECT *` was working somewhat by chance (probably by the order of the joins?).

And I think I'll need to edit this PR to omit whichever `args` we weren't actually using.

**Comment by PierreLeGuen** [comment]
@ryancwalsh, that is an interesting observation. It's surprising that duplicates are deleted by default. Let's reduce the scope of the SELECT in another PR?

**Comment by ryancwalsh** [comment]
@PierreLeGuen That sounds fine to me. Merging.

**Pull request merged**
